micronaut:
  application:
    name: dataDemo
datasources:
  default:
    url: jdbc:h2:mem:devDb;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE;MODE=PostgreSQL;DATABASE_TO_UPPER=false
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    dialect: H2
netty:
  default:
    allocator:
      max-order: 3
jpa.default:
  packages-to-scan:
    - 'com.example'
flyway.datasources.default: true
flyway:
  datasources:
    default:
      locations: classpath:db/migrations